# Generated by Django 5.2.5 on 2025-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
